ALTER TABLE `arbimon2`.`projects`
ADD COLUMN `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TRIGGER projects_update BEFORE UPDATE ON `arbimon2`.`projects` FOR EACH ROW SET NEW.updated_at = NOW();
