/* jshint node:true */
'use strict';

// Guard for app/utils/soundscape-grid.js (2026-09-26, operator goifirr 11:54):
// the node decoder + preview-matrix renderer must reproduce the AUTHORITATIVE
// python writer's output bit-for-bit. The fixture (test/soundscape-grid-fixture.json)
// was generated by soundscapes/old/soundscape/grid.py (encode_grid + preview)
// in the prod job image: a 6x4 synthetic grid with empty / single-amp /
// unsorted-multi-amp / extreme-value (0, 1e-30, 3.4e38) cells, previewed in 6
// settings modes (plain, absolute + relative threshold, normalized with a norm
// vector, normalized+relative, visual_max).
//
// Run: node test/soundscape-grid.test.js

const assert = require('assert');
const zlib = require('zlib');
const path = require('path');

const root = path.join(__dirname, '..');
const sg = require(path.join(root, 'app/utils/soundscape-grid.js'));
const fx = JSON.parse(require('fs').readFileSync(path.join(__dirname, 'soundscape-grid-fixture.json'), 'utf8'));

let pass = 0, fail = 0;
function ok (label, cond) { try { assert(cond); console.log('  ok   ' + label); pass++; } catch (e) { console.log('  FAIL ' + label + '  ' + e.message); fail++; } }

const gridBuf = Buffer.from(fx.grid_b64, 'base64');
const meta = fx.meta;
const gridRow = { width: meta.width, height: meta.height, offsetx: meta.offsetx, max_count: meta.max_count, max_amp: meta.max_amp, grid: gridBuf, norm_vector: null };

console.log('decode');
const d = sg.decodeGrid(gridBuf, meta.width, meta.height);
ok('counts shape', d.counts.length === 24 && d.cells.length === 24);
ok('cell (y=0,x=0) count 3', d.counts[0] === 3);
ok('cell amps sorted ascending', Array.from(d.cells[0]).join(',') === '0.25,0.5,0.75');
ok('extreme values round-trip to float32 precision (amps sorted ascending by the encoder)', d.cells[1 * 6 + 3][0] === Math.fround(1e-30) && d.cells[2 * 6 + 2][0] === 0.0 && d.cells[2 * 6 + 2][1] === Math.fround(12345.678) && d.cells[3 * 6 + 5][0] === Math.fround(3.4e38));
ok('empty cell is empty', d.counts[5] === 0 && d.cells[5].length === 0);

console.log('countAbove');
ok('binary search semantics (strictly greater)', sg.countAbove(Float32Array.from([0.1, 0.4, 0.9]), Math.fround(0.4)) === 1 && sg.countAbove(Float32Array.from([0.1, 0.4, 0.9]), 0) === 3);

console.log('preview parity vs python grid.py (6 modes)');
const MODES = {
    plain: { visual_max_value: null, normalized: 0, threshold: 0, threshold_type: null },
    abs_threshold: { visual_max_value: null, normalized: 0, threshold: 0.4, threshold_type: null },
    rel_threshold: { visual_max_value: null, normalized: 0, threshold: 0.25, threshold_type: 'relative-to-peak-maximum' },
    normalized: { visual_max_value: null, normalized: 1, threshold: 0, threshold_type: null },
    normalized_rel: { visual_max_value: null, normalized: 1, threshold: 0.5, threshold_type: 'relative-to-peak-maximum' },
    visual_max: { visual_max_value: 1.5, normalized: 0, threshold: 0, threshold_type: null }
};
for (const [name, settings] of Object.entries(MODES)) {
    const row = Object.assign({}, gridRow, { norm_vector: name.startsWith('normalized') ? fx.nv : null });
    const mine = sg.previewMatrix(row, settings);
    const theirs = zlib.gunzipSync(Buffer.from(fx.previews[name], 'base64'));
    ok(name + ' byte-identical', Buffer.from(mine.buffer, mine.byteOffset, mine.byteLength).equals(theirs));
}

console.log('preview gzip storage shape');
const m = sg.previewMatrix(Object.assign({}, gridRow), MODES.plain);
ok('gunzip(gzipPreview(m)) == m', zlib.gunzipSync(sg.gzipPreview(m)).equals(Buffer.from(m.buffer, m.byteOffset, m.byteLength)));

console.log('wiring (shipped source)');
const fs = require('fs');
const route = fs.readFileSync(path.join(root, 'app/routes/data-api/project/soundscapes.js'), 'utf8');
const model = fs.readFileSync(path.join(root, 'app/model/soundscapes.js'), 'utf8');
const assets = fs.readFileSync(path.join(root, 'app/routes/data-api/arbimon2-assets.js'), 'utf8');
const recs = fs.readFileSync(path.join(root, 'app/routes/data-api/project/recordings.js'), 'utf8');
ok('/grid route serves getGrid', /router\.get\('\/:soundscape\/grid'/.test(route) && /model\.soundscapes\.getGrid\(req\.soundscape\.id/.test(route));
ok('scale route recomputes preview', /updateGridPreview/.test(route) && /previewMatrix/.test(route));
ok('png handler tries the stored preview first', /previewPng/.test(assets) && /fetchSCIDX/.test(assets));
ok('membership route is project-scoped via findByIdInProjectAsync', /router\.get\('\/:recordingId\/soundscapes'/.test(recs) && /findByIdInProjectAsync/.test(recs));
ok('model has getGrid + updateGridPreview + findByRecordingAsync', /getGrid: function/.test(model) && /updateGridPreview: function/.test(model) && /findByRecordingAsync: function/.test(model));

setTimeout(() => { console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0); }, 50);
