version: "3.8"
include:
  - ./db/docker-compose.yaml
services:
  app:
    image: arbimon
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: arbimon
    ports:
      - "3000:3000"
    volumes:
      - $PWD/app:/app/app
      - $PWD/assets:/app/assets
      - $PWD/config:/app/config
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_DATABASE=arbimon2
      - DB_USER=admin
      - DB_PASSWORD=admin-secret
      - REDIS_URL=redis://redis:6379
    command: ["./node_modules/.bin/gulp", "watch"]
    depends_on:
      - mysql
      - redis
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes: 
      - data-redis:/data
volumes:
  data-redis:
